FROM debian:bullseye-slim

ENV container docker
ENV LC_ALL C
ENV DEBIAN_FRONTEND noninteractive

# Don't start any optional services except for the few we need.
RUN find /etc/systemd/system \
    /lib/systemd/system \
    -path '*.wants/*' \
    -not -name '*journald*' \
    -not -name '*systemd-tmpfiles*' \
    -not -name '*systemd-user-sessions*' \
    -exec rm \{} \;


RUN apt-get update && \
    apt-get install -y apt-utils \
                       iproute2 \
                       dbus \
                       systemd \
                       python3 \
                       python3-apt \
                       sudo \
                       gpg \
                       ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN systemctl set-default multi-user.target
RUN systemctl mask dev-hugepages.mount sys-fs-fuse-connections.mount

STOPSIGNAL SIGRTMIN+3

CMD ["/sbin/init"]
